### ISSUE TITLE
URL ID fixing broken for the ids #url, #ur, #rl, #u, #r, #l

### ISSUE THREAD

**Issue by MacDue** [elderapo/react-svg-unique-id#64]
Found this issue with some of my SVGs. Your id replacement code both ``fixPropWithUrl``, and ``getHookedXlinkHref`` won't work with any of these ids: #url, #ur, #rl, #u, #r, #l.

This is because you just replace the old id with the new id in the prop:
```js
return prop.replace(id, fixedId)
```
When my id is ``#l`` (so the prop is ``url(#l)``) that results in something like ``ur___SVG_ID__2__10___(#l)``

A simple fix would be to do
```js
return `url(#${fixedId})`
```
Instead

**Comment by MacDue** [comment]
I have published a fixed package here: https://www.npmjs.com/package/svg-unique-id-react (since I needed it working)

**Comment by elderapo** [comment]
Thanks for reporting this bug. As bot said, the new fixed version has been released.
